### ISSUE TITLE
How can convert to onnx from original repo

### ISSUE THREAD

**Issue by lucasjinreal** [SyGoing/LFFD-MNN#4]
I know is not this repo issue, but how did u guys able to convert to onnx? with original repo, I got some error:

```
INFO:root:Output node is: conv20_3_bbox
Traceback (most recent call last):
  File "to_onnx.py", line 39, in <module>
    generate_onnx_file()
  File "to_onnx.py", line 29, in generate_onnx_file
    onnx_mxnet.export_model(net_symbol, net_params, [input_shape], numpy.float32, onnx_path, verbose=True)
  File "/usr/local/lib/python3.5/dist-packages/mxnet/contrib/onnx/mx2onnx/export_model.py", line 87, in export_model
    verbose=verbose)
  File "/usr/local/lib/python3.5/dist-packages/mxnet/contrib/onnx/mx2onnx/export_onnx.py", line 312, in create_onnx_graph_proto
    checker.check_graph(graph)
  File "/usr/local/lib/python3.5/dist-packages/onnx/checker.py", line 53, in checker
    proto.SerializeToString(), ctx)
onnx.onnx_cpp2py_export.checker.ValidationError: Node (slice_axis20) has input size 1 not in range [min=3, max=5].

==> Context: Bad node spec: input: "softmax0" output: "slice_axis20" name: "slice_axis20" op_type: "Slice" attribute { name: "axes" ints: 1 type: INTS } attribute { name: "ends" ints: 1 type: INTS } attribute { name: "starts" ints: 0 type: INTS }

```

I am using the every newest version of mxnet and onnx

**Comment by SyGoing** [comment]
@jinfagang, please read the README.md carefully
